import { ClientLayout } from '@/core/components/client-layout';
// import { ThemeProvider } from '@/core/hooks/use-theme';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';
import './locomotive.css';

const aperkuSans = localFont({
    src: [
        {
            path: './fonts/ApercuProBlack.otf',
            weight: '900',
            style: 'normal',
        },
        {
            path: './fonts/ApercuProBold.otf',
            weight: '700',
            style: 'normal',
        },
        {
            path: './fonts/ApercuProExtraLight.otf',
            weight: '200',
            style: 'normal',
        },
        {
            path: './fonts/ApercuProLight.otf',
            weight: '300',
            style: 'normal',
        },
        {
            path: './fonts/ApercuProMedium.otf',
            weight: '500',
            style: 'normal',
        },
        {
            path: './fonts/ApercuProRegular.otf',
            weight: '400',
            style: 'normal',
        },
        {
            path: './fonts/ApercuProThin.otf',
            weight: '100',
            style: 'normal',
        },
    ],
    variable: '--font-aperku-sans',
});

const aperkuSansMono = localFont({
    src: [
        {
            path: './fonts/ApercuMonoProBold.otf',
            weight: '700',
            style: 'normal',
        },
        {
            path: './fonts/ApercuMonoProLight.otf',
            weight: '300',
            style: 'normal',
        },
        {
            path: './fonts/ApercuMonoProMedium.otf',
            weight: '500',
            style: 'normal',
        },
        {
            path: './fonts/ApercuMonoProRegular.otf',
            weight: '400',
            style: 'normal',
        },
    ],
    variable: '--font-aperku-sans-mono',
});

const voyageBold = localFont({
    src: [
        {
            path: './fonts/Voyage-Bold.otf',
            weight: '700',
            style: 'normal',
        },
    ],
    variable: '--font-voyage',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${aperkuSans.variable} ${aperkuSansMono.variable} ${voyageBold.variable}`}
        >
            <body
                className={`${aperkuSans.variable} ${aperkuSansMono.variable} ${voyageBold.variable} antialiased bg-[#FAF1E5]`}
            >
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    );
}
